export const seed = {
  users: [
    { id: "user-admin", email: "admin@boarding.test", fullName: "Platform Admin", role: "SUPER_ADMIN", demoPassword: "admin123" },
    { id: "user-rivera", email: "rivera@boarding.test", fullName: "Mara Rivera", role: "LANDLORD", landlordId: "landlord-rivera", demoPassword: "password123" },
    { id: "user-santos", email: "santos@boarding.test", fullName: "Eli Santos", role: "LANDLORD", landlordId: "landlord-santos", demoPassword: "password123" }
  ],
  landlords: [
    { id: "landlord-rivera", fullName: "Mara Rivera", businessName: "Rivera Homes", email: "rivera@boarding.test", contactNumber: "+63 917 100 2000", address: "Makati City", status: "Active", maxProperties: 3, currentPropertyCount: 2, subscriptionPlan: "Growth", subscriptionExpiresAt: "2026-12-31", lastLoginAt: "2026-07-28", notes: "Allows custom theme." },
    { id: "landlord-santos", fullName: "Eli Santos", businessName: "Santos Stay", email: "santos@boarding.test", contactNumber: "+63 918 300 4000", address: "Quezon City", status: "Active", maxProperties: 1, currentPropertyCount: 1, subscriptionPlan: "Starter", subscriptionExpiresAt: "2026-10-15", lastLoginAt: "2026-07-25", notes: "Near property limit." },
    { id: "landlord-cruz", fullName: "Nina Cruz", businessName: "Cruz Rentals", email: "cruz@boarding.test", contactNumber: "+63 919 500 6000", address: "Pasig City", status: "Suspended", maxProperties: 5, currentPropertyCount: 0, subscriptionPlan: "Enterprise", subscriptionExpiresAt: "2026-09-01", lastLoginAt: "2026-06-20", notes: "Suspended for billing review." }
  ],
  properties: [
    { id: "prop-aurora", landlordId: "landlord-rivera", name: "Aurora Boarding House", code: "ABH-001", address: "123 Aurora St, Makati", contactNumber: "+63 2 8888 1001", numberOfFloors: 3, totalUnits: 12, occupiedUnits: 8, vacantUnits: 2, reservedUnits: 1, maintenanceUnits: 1, manager: "Leah Ramos", status: "Active", monthlyExpectedRent: 106500, collectedThisMonth: 81200, outstanding: 25300, buildingViewTemplate: "modern-apartment" },
    { id: "prop-maple", landlordId: "landlord-rivera", name: "Maple Residences", code: "MAP-002", address: "41 Maple Ave, Makati", contactNumber: "+63 2 8888 1002", numberOfFloors: 2, totalUnits: 10, occupiedUnits: 8, vacantUnits: 2, manager: "Noel Vega", status: "Active", monthlyExpectedRent: 98000, collectedThisMonth: 76000, outstanding: 22000 },
    { id: "prop-santos", landlordId: "landlord-santos", name: "Santos Corner Boarding House", code: "SCB-001", address: "9 East Road, Quezon City", contactNumber: "+63 2 7777 3000", numberOfFloors: 4, totalUnits: 24, occupiedUnits: 20, vacantUnits: 4, manager: "Eli Santos", status: "Active", monthlyExpectedRent: 210000, collectedThisMonth: 185000, outstanding: 25000 }
  ],
  floors: [
    { id: "floor-aurora-1", landlordId: "landlord-rivera", propertyId: "prop-aurora", name: "Floor 1", floorNumber: 1, displayOrder: 1, description: "Ground-level rooms near the main entry.", status: "Active" },
    { id: "floor-aurora-2", landlordId: "landlord-rivera", propertyId: "prop-aurora", name: "Floor 2", floorNumber: 2, displayOrder: 2, description: "Central residential floor with balcony access.", status: "Active" },
    { id: "floor-aurora-3", landlordId: "landlord-rivera", propertyId: "prop-aurora", name: "Floor 3", floorNumber: 3, displayOrder: 3, description: "Upper floor with reserved and premium rooms.", status: "Active" },
    { id: "floor-maple-2", landlordId: "landlord-rivera", propertyId: "prop-maple", name: "Floor 2", floorNumber: 2, displayOrder: 2, description: "Default migrated floor for Maple units.", status: "Active" },
    { id: "floor-santos-1", landlordId: "landlord-santos", propertyId: "prop-santos", name: "Floor 1", floorNumber: 1, displayOrder: 1, description: "Default migrated floor.", status: "Active" }
  ],
  units: [
    { id: "unit-101", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-1", unitNumber: "101", unitName: "Front Studio", floor: "1", unitType: "Studio", monthlyRent: 8500, securityDeposit: 8500, maxOccupants: 2, currentOccupantCount: 1, electricityBillingMethod: "Metered", waterBillingMethod: "Shared equally", status: "Occupied", tenantName: "Ana Dela Cruz" },
    { id: "unit-102", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-1", unitNumber: "102", unitName: "Shared Room", floor: "1", unitType: "Bedspace", monthlyRent: 7000, securityDeposit: 7000, maxOccupants: 4, currentOccupantCount: 3, electricityBillingMethod: "Included in rent", waterBillingMethod: "Included in rent", status: "Occupied", tenantName: "Bea Santos, Ian Cruz, Kit Ramos" },
    { id: "unit-103", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-1", unitNumber: "103", unitName: "Garden Room", floor: "1", unitType: "Single", monthlyRent: 6800, securityDeposit: 6800, maxOccupants: 1, currentOccupantCount: 0, electricityBillingMethod: "Fixed monthly", waterBillingMethod: "Fixed monthly", status: "Vacant", tenantName: "" },
    { id: "unit-104", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-1", unitNumber: "104", unitName: "Corner Studio", floor: "1", unitType: "Studio", monthlyRent: 8800, securityDeposit: 8800, maxOccupants: 2, currentOccupantCount: 2, electricityBillingMethod: "Metered", waterBillingMethod: "Shared equally", status: "Occupied", tenantName: "Nico Reyes, Lara Tan" },
    { id: "unit-201a", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-2", unitNumber: "201", unitName: "Balcony Studio", floor: "2", unitType: "Studio", monthlyRent: 9200, securityDeposit: 9200, maxOccupants: 2, currentOccupantCount: 1, electricityBillingMethod: "Metered", waterBillingMethod: "Metered", status: "Occupied", tenantName: "Mika Lopez" },
    { id: "unit-202", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-2", unitNumber: "202", unitName: "North Room", floor: "2", unitType: "Single", monthlyRent: 7900, securityDeposit: 7900, maxOccupants: 1, currentOccupantCount: 1, electricityBillingMethod: "Metered", waterBillingMethod: "Fixed monthly", status: "Occupied", tenantName: "Carlo Yu" },
    { id: "unit-203", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-2", unitNumber: "203", unitName: "Premium Studio", floor: "2", unitType: "Studio", monthlyRent: 9500, securityDeposit: 9500, maxOccupants: 2, currentOccupantCount: 2, electricityBillingMethod: "Metered", waterBillingMethod: "Metered", status: "Occupied", tenantName: "Juan Dela Cruz, Mei Chen" },
    { id: "unit-204", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-2", unitNumber: "204", unitName: "Service Room", floor: "2", unitType: "Single", monthlyRent: 7600, securityDeposit: 7600, maxOccupants: 1, currentOccupantCount: 0, electricityBillingMethod: "Manual amount", waterBillingMethod: "Manual amount", status: "Under Maintenance", tenantName: "" },
    { id: "unit-301", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-3", unitNumber: "301", unitName: "Sky Studio", floor: "3", unitType: "Studio", monthlyRent: 9800, securityDeposit: 9800, maxOccupants: 2, currentOccupantCount: 1, electricityBillingMethod: "Metered", waterBillingMethod: "Metered", status: "Occupied", tenantName: "Rafi Garcia" },
    { id: "unit-302", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-3", unitNumber: "302", unitName: "Reserved Room", floor: "3", unitType: "Studio", monthlyRent: 9600, securityDeposit: 9600, maxOccupants: 2, currentOccupantCount: 0, electricityBillingMethod: "Metered", waterBillingMethod: "Metered", status: "Reserved", tenantName: "Reserved for Sofia Lim" },
    { id: "unit-303", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-3", unitNumber: "303", unitName: "East Single", floor: "3", unitType: "Single", monthlyRent: 7300, securityDeposit: 7300, maxOccupants: 1, currentOccupantCount: 0, electricityBillingMethod: "Included in rent", waterBillingMethod: "Included in rent", status: "Vacant", tenantName: "" },
    { id: "unit-304", landlordId: "landlord-rivera", propertyId: "prop-aurora", floorId: "floor-aurora-3", unitNumber: "304", unitName: "Rooftop Studio", floor: "3", unitType: "Studio", monthlyRent: 10500, securityDeposit: 10500, maxOccupants: 2, currentOccupantCount: 1, electricityBillingMethod: "Metered", waterBillingMethod: "Metered", status: "Occupied", tenantName: "Tess Aquino" },
    { id: "unit-201", landlordId: "landlord-rivera", propertyId: "prop-maple", floorId: "floor-maple-2", unitNumber: "201", unitName: "Maple Studio", floor: "2", unitType: "Studio", monthlyRent: 12000, securityDeposit: 12000, maxOccupants: 2, currentOccupantCount: 2, electricityBillingMethod: "Metered", waterBillingMethod: "Metered", status: "Occupied", tenantName: "Marco Reyes" },
    { id: "unit-s1", landlordId: "landlord-santos", propertyId: "prop-santos", floorId: "floor-santos-1", unitNumber: "A1", unitName: "A1", floor: "1", unitType: "Single", monthlyRent: 9000, securityDeposit: 9000, maxOccupants: 1, currentOccupantCount: 1, electricityBillingMethod: "Metered", waterBillingMethod: "Fixed monthly", status: "Occupied", tenantName: "Paolo Lim" }
  ],
  tenants: [
    { id: "tenant-ana", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-101", fullName: "Ana Dela Cruz", email: "ana@example.com", contactNumber: "+63 917 111 1111", emergencyContactName: "Rosa Dela Cruz", emergencyContactNumber: "+63 917 222 2222", validIdType: "UMID", validIdNumber: "UM-2211", monthlyRent: 8500, moveInDate: "2026-01-10", contractEndDate: "2026-12-31", billingDueDay: 5, status: "Active" },
    { id: "tenant-bea", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-102", fullName: "Bea Santos", email: "bea@example.com", contactNumber: "+63 917 101 0102", emergencyContactName: "Manny Santos", emergencyContactNumber: "+63 917 201 0102", validIdType: "National ID", validIdNumber: "NID-102", monthlyRent: 7000, moveInDate: "2026-02-01", contractEndDate: "2027-01-31", billingDueDay: 5, status: "Active" },
    { id: "tenant-nico", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-104", fullName: "Nico Reyes", email: "nico@example.com", contactNumber: "+63 917 101 0104", emergencyContactName: "Lara Tan", emergencyContactNumber: "+63 917 201 0104", validIdType: "Passport", validIdNumber: "P-104", monthlyRent: 8800, moveInDate: "2026-02-12", contractEndDate: "2027-02-11", billingDueDay: 7, status: "Active" },
    { id: "tenant-mika", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-201a", fullName: "Mika Lopez", email: "mika@example.com", contactNumber: "+63 917 101 0201", emergencyContactName: "Tina Lopez", emergencyContactNumber: "+63 917 201 0201", validIdType: "UMID", validIdNumber: "UM-201", monthlyRent: 9200, moveInDate: "2026-04-03", contractEndDate: "2027-04-02", billingDueDay: 10, status: "Active" },
    { id: "tenant-carlo", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-202", fullName: "Carlo Yu", email: "carlo@example.com", contactNumber: "+63 917 101 0202", emergencyContactName: "Mina Yu", emergencyContactNumber: "+63 917 201 0202", validIdType: "Driver License", validIdNumber: "DL-202", monthlyRent: 7900, moveInDate: "2026-05-01", contractEndDate: "2027-04-30", billingDueDay: 10, status: "Active" },
    { id: "tenant-juan", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-203", fullName: "Juan Dela Cruz", email: "juan@example.com", contactNumber: "+63 917 101 0203", emergencyContactName: "Elena Cruz", emergencyContactNumber: "+63 917 201 0203", validIdType: "National ID", validIdNumber: "NID-203", monthlyRent: 9500, moveInDate: "2026-03-20", contractEndDate: "2027-03-19", billingDueDay: 5, status: "Active" },
    { id: "tenant-rafi", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-301", fullName: "Rafi Garcia", email: "rafi@example.com", contactNumber: "+63 917 101 0301", emergencyContactName: "Amor Garcia", emergencyContactNumber: "+63 917 201 0301", validIdType: "UMID", validIdNumber: "UM-301", monthlyRent: 9800, moveInDate: "2026-01-22", contractEndDate: "2026-12-21", billingDueDay: 12, status: "Active" },
    { id: "tenant-tess", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-304", fullName: "Tess Aquino", email: "tess@example.com", contactNumber: "+63 917 101 0304", emergencyContactName: "Paula Aquino", emergencyContactNumber: "+63 917 201 0304", validIdType: "Passport", validIdNumber: "P-304", monthlyRent: 10500, moveInDate: "2026-06-01", contractEndDate: "2027-05-31", billingDueDay: 15, status: "Active" },
    { id: "tenant-marco", landlordId: "landlord-rivera", propertyId: "prop-maple", unitId: "unit-201", fullName: "Marco Reyes", email: "marco@example.com", contactNumber: "+63 917 333 3333", emergencyContactName: "Mila Reyes", emergencyContactNumber: "+63 917 444 4444", validIdType: "Driver License", validIdNumber: "DL-5533", monthlyRent: 12000, moveInDate: "2026-03-01", contractEndDate: "2027-02-28", billingDueDay: 10, status: "Active" },
    { id: "tenant-paolo", landlordId: "landlord-santos", propertyId: "prop-santos", unitId: "unit-s1", fullName: "Paolo Lim", email: "paolo@example.com", contactNumber: "+63 917 555 5555", emergencyContactName: "Liza Lim", emergencyContactNumber: "+63 917 666 6666", validIdType: "Passport", validIdNumber: "P-7788", monthlyRent: 9000, moveInDate: "2026-05-15", contractEndDate: "2026-11-15", billingDueDay: 5, status: "Active" }
  ],
  leases: [
    { id: "lease-ana", landlordId: "landlord-rivera", tenantId: "tenant-ana", propertyId: "prop-aurora", unitId: "unit-101", tenantName: "Ana Dela Cruz", propertyName: "Aurora Boarding House", unitNumber: "101", monthlyRent: 8500, securityDeposit: 8500, startsAt: "2026-01-10", endsAt: "2026-12-31", status: "Active" },
    { id: "lease-bea", landlordId: "landlord-rivera", tenantId: "tenant-bea", propertyId: "prop-aurora", unitId: "unit-102", tenantName: "Bea Santos", propertyName: "Aurora Boarding House", unitNumber: "102", monthlyRent: 7000, securityDeposit: 7000, startsAt: "2026-02-01", endsAt: "2027-01-31", status: "Active" },
    { id: "lease-nico", landlordId: "landlord-rivera", tenantId: "tenant-nico", propertyId: "prop-aurora", unitId: "unit-104", tenantName: "Nico Reyes", propertyName: "Aurora Boarding House", unitNumber: "104", monthlyRent: 8800, securityDeposit: 8800, startsAt: "2026-02-12", endsAt: "2027-02-11", status: "Active" },
    { id: "lease-mika", landlordId: "landlord-rivera", tenantId: "tenant-mika", propertyId: "prop-aurora", unitId: "unit-201a", tenantName: "Mika Lopez", propertyName: "Aurora Boarding House", unitNumber: "201", monthlyRent: 9200, securityDeposit: 9200, startsAt: "2026-04-03", endsAt: "2027-04-02", status: "Active" },
    { id: "lease-carlo", landlordId: "landlord-rivera", tenantId: "tenant-carlo", propertyId: "prop-aurora", unitId: "unit-202", tenantName: "Carlo Yu", propertyName: "Aurora Boarding House", unitNumber: "202", monthlyRent: 7900, securityDeposit: 7900, startsAt: "2026-05-01", endsAt: "2027-04-30", status: "Active" },
    { id: "lease-juan", landlordId: "landlord-rivera", tenantId: "tenant-juan", propertyId: "prop-aurora", unitId: "unit-203", tenantName: "Juan Dela Cruz", propertyName: "Aurora Boarding House", unitNumber: "203", monthlyRent: 9500, securityDeposit: 9500, startsAt: "2026-03-20", endsAt: "2027-03-19", status: "Active" },
    { id: "lease-rafi", landlordId: "landlord-rivera", tenantId: "tenant-rafi", propertyId: "prop-aurora", unitId: "unit-301", tenantName: "Rafi Garcia", propertyName: "Aurora Boarding House", unitNumber: "301", monthlyRent: 9800, securityDeposit: 9800, startsAt: "2026-01-22", endsAt: "2026-12-21", status: "Active" },
    { id: "lease-tess", landlordId: "landlord-rivera", tenantId: "tenant-tess", propertyId: "prop-aurora", unitId: "unit-304", tenantName: "Tess Aquino", propertyName: "Aurora Boarding House", unitNumber: "304", monthlyRent: 10500, securityDeposit: 10500, startsAt: "2026-06-01", endsAt: "2027-05-31", status: "Active" },
    { id: "lease-marco", landlordId: "landlord-rivera", tenantId: "tenant-marco", propertyId: "prop-maple", unitId: "unit-201", tenantName: "Marco Reyes", propertyName: "Maple Residences", unitNumber: "201", monthlyRent: 12000, securityDeposit: 12000, startsAt: "2026-03-01", endsAt: "2027-02-28", status: "Active" }
  ],
  billing: [
    { id: "bill-ana-jul", landlordId: "landlord-rivera", tenantId: "tenant-ana", tenantName: "Ana Dela Cruz", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-101", unitNumber: "101", billingPeriod: "2026-07", monthlyRent: 8500, electricityCharge: 920, waterCharge: 180, previousBalance: 0, penalty: 0, otherCharges: 0, discount: 0, totalAmountDue: 9600, amountPaid: 9600, remainingBalance: 0, dueDate: "2026-07-05", status: "Paid" },
    { id: "bill-bea-jul", landlordId: "landlord-rivera", tenantId: "tenant-bea", tenantName: "Bea Santos", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-102", unitNumber: "102", billingPeriod: "2026-07", monthlyRent: 7000, electricityCharge: 0, waterCharge: 0, previousBalance: 0, penalty: 0, otherCharges: 250, discount: 0, totalAmountDue: 7250, amountPaid: 7250, remainingBalance: 0, dueDate: "2026-07-05", status: "Paid" },
    { id: "bill-nico-jul", landlordId: "landlord-rivera", tenantId: "tenant-nico", tenantName: "Nico Reyes", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-104", unitNumber: "104", billingPeriod: "2026-07", monthlyRent: 8800, electricityCharge: 1030, waterCharge: 180, previousBalance: 0, penalty: 0, otherCharges: 0, discount: 0, totalAmountDue: 10010, amountPaid: 10010, remainingBalance: 0, dueDate: "2026-07-07", status: "Paid" },
    { id: "bill-mika-jul", landlordId: "landlord-rivera", tenantId: "tenant-mika", tenantName: "Mika Lopez", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-201a", unitNumber: "201", billingPeriod: "2026-07", monthlyRent: 9200, electricityCharge: 860, waterCharge: 410, previousBalance: 0, penalty: 0, otherCharges: 0, discount: 0, totalAmountDue: 10470, amountPaid: 10470, remainingBalance: 0, dueDate: "2026-07-10", status: "Paid" },
    { id: "bill-carlo-jul", landlordId: "landlord-rivera", tenantId: "tenant-carlo", tenantName: "Carlo Yu", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-202", unitNumber: "202", billingPeriod: "2026-07", monthlyRent: 7900, electricityCharge: 730, waterCharge: 350, previousBalance: 0, penalty: 0, otherCharges: 0, discount: 0, totalAmountDue: 8980, amountPaid: 4000, remainingBalance: 4980, dueDate: "2026-07-10", status: "Partially Paid" },
    { id: "bill-juan-jul", landlordId: "landlord-rivera", tenantId: "tenant-juan", tenantName: "Juan Dela Cruz", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-203", unitNumber: "203", billingPeriod: "2026-07", monthlyRent: 9500, electricityCharge: 1250, waterCharge: 480, previousBalance: 2500, penalty: 300, otherCharges: 0, discount: 0, totalAmountDue: 14030, amountPaid: 5000, remainingBalance: 9030, dueDate: "2026-07-05", status: "Overdue" },
    { id: "bill-rafi-jul", landlordId: "landlord-rivera", tenantId: "tenant-rafi", tenantName: "Rafi Garcia", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-301", unitNumber: "301", billingPeriod: "2026-07", monthlyRent: 9800, electricityCharge: 910, waterCharge: 430, previousBalance: 0, penalty: 0, otherCharges: 0, discount: 200, totalAmountDue: 10940, amountPaid: 0, remainingBalance: 10940, dueDate: "2026-07-12", status: "Unpaid" },
    { id: "bill-tess-jul", landlordId: "landlord-rivera", tenantId: "tenant-tess", tenantName: "Tess Aquino", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-304", unitNumber: "304", billingPeriod: "2026-07", monthlyRent: 10500, electricityCharge: 1080, waterCharge: 430, previousBalance: 0, penalty: 0, otherCharges: 0, discount: 0, totalAmountDue: 12010, amountPaid: 12010, remainingBalance: 0, dueDate: "2026-07-15", status: "Paid" },
    { id: "bill-marco-jul", landlordId: "landlord-rivera", tenantId: "tenant-marco", tenantName: "Marco Reyes", propertyId: "prop-maple", propertyName: "Maple Residences", unitId: "unit-201", unitNumber: "201", billingPeriod: "2026-07", monthlyRent: 12000, electricityCharge: 1400, waterCharge: 520, previousBalance: 2500, penalty: 150, otherCharges: 0, discount: 0, totalAmountDue: 16570, amountPaid: 8000, remainingBalance: 8570, dueDate: "2026-07-10", status: "Partially Paid" },
    { id: "bill-ana-jun", landlordId: "landlord-rivera", tenantId: "tenant-ana", tenantName: "Ana Dela Cruz", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitId: "unit-101", unitNumber: "101", billingPeriod: "2026-06", monthlyRent: 8500, electricityCharge: 870, waterCharge: 180, previousBalance: 0, penalty: 300, otherCharges: 0, discount: 0, totalAmountDue: 9850, amountPaid: 0, remainingBalance: 9850, dueDate: "2026-06-05", status: "Overdue" }
  ],
  electricity: [
    { id: "elec-ana-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-101", tenantName: "Ana Dela Cruz", billingMonth: "2026-07", previousReading: 1220, currentReading: 1320, consumption: 100, ratePerUnit: 9.2, fixedCharge: 0, amount: 920, readingDate: "2026-07-01", recordedBy: "Mara Rivera" },
    { id: "elec-nico-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-104", tenantName: "Nico Reyes", billingMonth: "2026-07", previousReading: 800, currentReading: 903, consumption: 103, ratePerUnit: 10, fixedCharge: 0, amount: 1030, readingDate: "2026-07-02", recordedBy: "Mara Rivera" },
    { id: "elec-mika-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-201a", tenantName: "Mika Lopez", billingMonth: "2026-07", previousReading: 430, currentReading: 516, consumption: 86, ratePerUnit: 10, fixedCharge: 0, amount: 860, readingDate: "2026-07-02", recordedBy: "Mara Rivera" },
    { id: "elec-carlo-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-202", tenantName: "Carlo Yu", billingMonth: "2026-07", previousReading: 720, currentReading: 793, consumption: 73, ratePerUnit: 10, fixedCharge: 0, amount: 730, readingDate: "2026-07-02", recordedBy: "Mara Rivera" },
    { id: "elec-juan-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-203", tenantName: "Juan Dela Cruz", billingMonth: "2026-07", previousReading: 950, currentReading: 1075, consumption: 125, ratePerUnit: 10, fixedCharge: 0, amount: 1250, readingDate: "2026-07-03", recordedBy: "Mara Rivera" },
    { id: "elec-rafi-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-301", tenantName: "Rafi Garcia", billingMonth: "2026-07", previousReading: 610, currentReading: 701, consumption: 91, ratePerUnit: 10, fixedCharge: 0, amount: 910, readingDate: "2026-07-03", recordedBy: "Mara Rivera" },
    { id: "elec-tess-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-304", tenantName: "Tess Aquino", billingMonth: "2026-07", previousReading: 300, currentReading: 408, consumption: 108, ratePerUnit: 10, fixedCharge: 0, amount: 1080, readingDate: "2026-07-04", recordedBy: "Mara Rivera" },
    { id: "elec-marco-jul", landlordId: "landlord-rivera", propertyId: "prop-maple", unitId: "unit-201", tenantName: "Marco Reyes", billingMonth: "2026-07", previousReading: 540, currentReading: 680, consumption: 140, ratePerUnit: 10, fixedCharge: 0, amount: 1400, readingDate: "2026-07-02", recordedBy: "Mara Rivera" }
  ],
  water: [
    { id: "water-aurora-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-101", tenantName: "Ana Dela Cruz", billingMonth: "2026-07", previousReading: 210, currentReading: 228, consumption: 18, ratePerUnit: 10, fixedCharge: 0, totalPropertyBill: 2700, occupiedUnitCount: 15, amount: 180, calculationNote: "2700 divided across 15 occupied units", readingDate: "2026-07-01" },
    { id: "water-nico-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-104", tenantName: "Nico Reyes", billingMonth: "2026-07", previousReading: 160, currentReading: 178, consumption: 18, ratePerUnit: 10, fixedCharge: 0, totalPropertyBill: 2700, occupiedUnitCount: 15, amount: 180, calculationNote: "2700 divided across 15 occupied units", readingDate: "2026-07-01" },
    { id: "water-mika-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-201a", tenantName: "Mika Lopez", billingMonth: "2026-07", previousReading: 70, currentReading: 111, consumption: 41, ratePerUnit: 10, fixedCharge: 0, totalPropertyBill: 0, occupiedUnitCount: null, amount: 410, calculationNote: "41 cubic meters x 10", readingDate: "2026-07-02" },
    { id: "water-carlo-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-202", tenantName: "Carlo Yu", billingMonth: "2026-07", previousReading: 82, currentReading: 117, consumption: 35, ratePerUnit: 10, fixedCharge: 0, totalPropertyBill: 0, occupiedUnitCount: null, amount: 350, calculationNote: "35 cubic meters x 10", readingDate: "2026-07-02" },
    { id: "water-juan-jul", landlordId: "landlord-rivera", propertyId: "prop-aurora", unitId: "unit-203", tenantName: "Juan Dela Cruz", billingMonth: "2026-07", previousReading: 120, currentReading: 168, consumption: 48, ratePerUnit: 10, fixedCharge: 0, totalPropertyBill: 0, occupiedUnitCount: null, amount: 480, calculationNote: "48 cubic meters x 10", readingDate: "2026-07-03" },
    { id: "water-maple-jul", landlordId: "landlord-rivera", propertyId: "prop-maple", unitId: "unit-201", tenantName: "Marco Reyes", billingMonth: "2026-07", previousReading: 90, currentReading: 116, consumption: 26, ratePerUnit: 20, fixedCharge: 0, totalPropertyBill: 0, occupiedUnitCount: null, amount: 520, calculationNote: "26 cubic meters x 20", readingDate: "2026-07-02" }
  ],
  payments: [
    { id: "pay-1001", landlordId: "landlord-rivera", officialReceiptNo: "OR-1001", tenantName: "Ana Dela Cruz", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitNumber: "101", billingStatement: "July 2026", paymentDate: "2026-07-04", amountPaid: 9600, paymentMethod: "GCash", referenceNumber: "GC-778800", receivedBy: "Mara Rivera", status: "Confirmed" },
    { id: "pay-1003", landlordId: "landlord-rivera", officialReceiptNo: "OR-1003", tenantName: "Bea Santos", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitNumber: "102", billingStatement: "July 2026", paymentDate: "2026-07-05", amountPaid: 7250, paymentMethod: "Cash", referenceNumber: "CASH", receivedBy: "Mara Rivera", status: "Confirmed" },
    { id: "pay-1004", landlordId: "landlord-rivera", officialReceiptNo: "OR-1004", tenantName: "Nico Reyes", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitNumber: "104", billingStatement: "July 2026", paymentDate: "2026-07-06", amountPaid: 10010, paymentMethod: "Maya", referenceNumber: "MY-0104", receivedBy: "Mara Rivera", status: "Confirmed" },
    { id: "pay-1005", landlordId: "landlord-rivera", officialReceiptNo: "OR-1005", tenantName: "Mika Lopez", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitNumber: "201", billingStatement: "July 2026", paymentDate: "2026-07-09", amountPaid: 10470, paymentMethod: "Bank Transfer", referenceNumber: "BT-0201", receivedBy: "Mara Rivera", status: "Confirmed" },
    { id: "pay-1006", landlordId: "landlord-rivera", officialReceiptNo: "OR-1006", tenantName: "Carlo Yu", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitNumber: "202", billingStatement: "July 2026", paymentDate: "2026-07-11", amountPaid: 4000, paymentMethod: "GCash", referenceNumber: "GC-0202", receivedBy: "Mara Rivera", status: "Confirmed" },
    { id: "pay-1007", landlordId: "landlord-rivera", officialReceiptNo: "OR-1007", tenantName: "Juan Dela Cruz", propertyId: "prop-aurora", propertyName: "Aurora Boarding House", unitNumber: "203", billingStatement: "July 2026", paymentDate: "2026-07-12", amountPaid: 5000, paymentMethod: "GCash", referenceNumber: "GC-0203", receivedBy: "Mara Rivera", status: "Confirmed" },
    { id: "pay-1002", landlordId: "landlord-rivera", officialReceiptNo: "OR-1002", tenantName: "Marco Reyes", propertyId: "prop-maple", propertyName: "Maple Residences", unitNumber: "201", billingStatement: "July 2026", paymentDate: "2026-07-12", amountPaid: 8000, paymentMethod: "Bank Transfer", referenceNumber: "BT-1100", receivedBy: "Mara Rivera", status: "Confirmed" }
  ],
  notifications: [
    { id: "notif-1", landlordId: "landlord-rivera", type: "Overdue rent", title: "Ana has an overdue June bill", message: "Remaining balance is PHP 9,850.", createdAt: "2026-07-29", readAt: null },
    { id: "notif-2", landlordId: "landlord-rivera", type: "Meter reading missing", title: "3 readings not yet entered", message: "Some vacant and occupied units have no July readings.", createdAt: "2026-07-28", readAt: null }
  ],
  themes: [
    { landlordId: "landlord-rivera", presetName: "Professional Blue", primaryColor: "#2563eb", secondaryColor: "#0f766e", accentColor: "#f59e0b", sidebarColor: "#111827", headerColor: "#ffffff", backgroundColor: "#f8fafc", textColor: "#111827", buttonStyle: "solid", borderRadius: "8px", businessName: "Rivera Homes", receiptHeader: "Rivera Homes Official Receipt", billingStatementHeader: "Rivera Homes Billing Statement" }
  ],
  auditLogs: [
    { id: "audit-1", landlordId: "landlord-rivera", user: "Mara Rivera", role: "LANDLORD", action: "PAYMENT_RECORDING", module: "Payments", recordId: "pay-1002", createdAt: "2026-07-12 09:15", ipAddress: "127.0.0.1" },
    { id: "audit-2", landlordId: "landlord-rivera", user: "Platform Admin", role: "SUPER_ADMIN", action: "SUBSCRIPTION_CHANGE", module: "Subscriptions", recordId: "landlord-rivera", createdAt: "2026-07-01 14:05", ipAddress: "127.0.0.1" }
  ],
  reports: ["Monthly rental collection", "Outstanding balances", "Overdue tenants", "Tenant ledger", "Payment history", "Rent roll", "Occupancy report", "Vacant-unit report", "Electricity consumption", "Water charges", "Revenue by property", "Collection efficiency"],
  landlordCharts: {
    collections: [
      { month: "Feb", expected: 210000, collected: 190000, electricity: 12800, water: 5100 },
      { month: "Mar", expected: 222000, collected: 206000, electricity: 13600, water: 5400 },
      { month: "Apr", expected: 238000, collected: 220000, electricity: 14100, water: 5600 },
      { month: "May", expected: 250000, collected: 231000, electricity: 15200, water: 6100 },
      { month: "Jun", expected: 260000, collected: 238000, electricity: 16100, water: 6200 },
      { month: "Jul", expected: 260000, collected: 212000, electricity: 17300, water: 6800 }
    ],
    occupancy: [
      { name: "Occupied", value: 23 },
      { name: "Vacant", value: 5 },
      { name: "Maintenance", value: 1 }
    ],
    revenueByProperty: [
      { name: "Aurora", value: 136000 },
      { name: "Maple", value: 76000 }
    ]
  },
  platformCharts: {
    registrations: [
      { month: "Mar", landlords: 1 },
      { month: "Apr", landlords: 2 },
      { month: "May", landlords: 2 },
      { month: "Jun", landlords: 3 },
      { month: "Jul", landlords: 3 }
    ],
    plans: [
      { name: "Starter", value: 1 },
      { name: "Growth", value: 1 },
      { name: "Enterprise", value: 1 }
    ]
  },
  settings: [
    { key: "supportModeRequiresAudit", value: true },
    { key: "defaultPropertyLimit", value: 1 },
    { key: "receiptPrefix", value: "OR" }
  ]
};
